services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: SCHEDULEDB
    volumes:
      - ./backup/postgres/data:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    restart: unless-stopped
    networks:
      - schedule-network

networks:
  schedule-network:
    driver: bridge



