services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    environment:
      username: user
      password: local
      db: SCHEDULEDB
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - schedule-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  schedule-network:
    driver: bridge

volumes:
  postgres-data:




