spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SCHEDULEDB
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
