spring:
    application:
        name: schedulecore
    mail:
        subjectDelete: "Seu Agendamento Foi Cancelado - "
        bodyDelete: "Seu Agendamento foi cancelado por você ou pelo administrador do sistema, por favor, em caso de dúvidas entrar em contato com time resposável. \n Dados do agendamento:\n"
        host: smtp.office365.com
        port: 587
        username: ${email}
        password: ${senha}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

server:
    port: 3000